name: Test-Workflow

on:
  push:
    branches:
      - develop
      - feature/*
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install
      run: npm install

    - name: npm lint
      run: npm run lint

    - name: npm build
      run: npm run build

    - name: npm test
      env:
        CLOUDFLARE_EMAIL: ${{ secrets.TESTS__CLOUDFLARE_EMAIL }}
        CLOUDFLARE_KEY: ${{ secrets.TESTS__CLOUDFLARE_KEY }}
        CLOUDFLARE_RECORDS: ${{ secrets.TESTS__CLOUDFLARE_RECORDS }}
      run: npm test -- --email=$CLOUDFLARE_EMAIL --key=$CLOUDFLARE_KEY --records=$CLOUDFLARE_RECORDS
